// Code generated by MockGen. DO NOT EDIT.
// Source: governance-api-go/cmd/listener/core (interfaces: BlockRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBlockRepository is a mock of BlockRepository interface.
type MockBlockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBlockRepositoryMockRecorder
}

// MockBlockRepositoryMockRecorder is the mock recorder for MockBlockRepository.
type MockBlockRepositoryMockRecorder struct {
	mock *MockBlockRepository
}

// NewMockBlockRepository creates a new mock instance.
func NewMockBlockRepository(ctrl *gomock.Controller) *MockBlockRepository {
	mock := &MockBlockRepository{ctrl: ctrl}
	mock.recorder = &MockBlockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockRepository) EXPECT() *MockBlockRepositoryMockRecorder {
	return m.recorder
}

// GetLatestProcessedBlock mocks base method.
func (m *MockBlockRepository) GetLatestProcessedBlock(arg0 context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestProcessedBlock", arg0)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestProcessedBlock indicates an expected call of GetLatestProcessedBlock.
func (mr *MockBlockRepositoryMockRecorder) GetLatestProcessedBlock(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestProcessedBlock", reflect.TypeOf((*MockBlockRepository)(nil).GetLatestProcessedBlock), arg0)
}

// UpdateLatestProcessedBlock mocks base method.
func (m *MockBlockRepository) UpdateLatestProcessedBlock(arg0 context.Context, arg1 *big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLatestProcessedBlock", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLatestProcessedBlock indicates an expected call of UpdateLatestProcessedBlock.
func (mr *MockBlockRepositoryMockRecorder) UpdateLatestProcessedBlock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLatestProcessedBlock", reflect.TypeOf((*MockBlockRepository)(nil).UpdateLatestProcessedBlock), arg0, arg1)
}
