// Code generated by MockGen. DO NOT EDIT.
// Source: governance-api-go/cmd/listener/core (interfaces: Decryptor)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	config "github.com/raylsnetwork/rayls-privacy-pnh-governance-api/config"
	types "github.com/raylsnetwork/rayls-privacy-pnh-governance-api/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDecryptor is a mock of Decryptor interface.
type MockDecryptor struct {
	ctrl     *gomock.Controller
	recorder *MockDecryptorMockRecorder
}

// MockDecryptorMockRecorder is the mock recorder for MockDecryptor.
type MockDecryptorMockRecorder struct {
	mock *MockDecryptor
}

// NewMockDecryptor creates a new mock instance.
func NewMockDecryptor(ctrl *gomock.Controller) *MockDecryptor {
	mock := &MockDecryptor{ctrl: ctrl}
	mock.recorder = &MockDecryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecryptor) EXPECT() *MockDecryptorMockRecorder {
	return m.recorder
}

// DecryptPayloadBytes mocks base method.
func (m *MockDecryptor) DecryptPayloadBytes(arg0 []byte, arg1 uint64, arg2 map[string]map[string]*types.IPNodeDataAndSecrets, arg3 types.SecretType) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptPayloadBytes", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptPayloadBytes indicates an expected call of DecryptPayloadBytes.
func (mr *MockDecryptorMockRecorder) DecryptPayloadBytes(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptPayloadBytes", reflect.TypeOf((*MockDecryptor)(nil).DecryptPayloadBytes), arg0, arg1, arg2, arg3)
}

// DecryptWithSalt mocks base method.
func (m *MockDecryptor) DecryptWithSalt(arg0, arg1 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptWithSalt", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptWithSalt indicates an expected call of DecryptWithSalt.
func (mr *MockDecryptorMockRecorder) DecryptWithSalt(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptWithSalt", reflect.TypeOf((*MockDecryptor)(nil).DecryptWithSalt), arg0, arg1)
}

// DecryptSwapPayload mocks base method.
func (m *MockDecryptor) DecryptSwapPayload(arg0, arg1 []byte, arg2 uint64, arg3 map[string]map[string]*types.IPNodeDataAndSecrets) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptSwapPayload", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DecryptSwapPayload indicates an expected call of DecryptSwapPayload.
func (mr *MockDecryptorMockRecorder) DecryptSwapPayload(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptSwapPayload", reflect.TypeOf((*MockDecryptor)(nil).DecryptSwapPayload), arg0, arg1, arg2, arg3)
}

// GatherParticipantsData mocks base method.
func (m *MockDecryptor) GatherParticipantsData(arg0 context.Context, arg1 *config.Config) (map[string]map[string]*types.IPNodeDataAndSecrets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GatherParticipantsData", arg0, arg1)
	ret0, _ := ret[0].(map[string]map[string]*types.IPNodeDataAndSecrets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GatherParticipantsData indicates an expected call of GatherParticipantsData.
func (mr *MockDecryptorMockRecorder) GatherParticipantsData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GatherParticipantsData", reflect.TypeOf((*MockDecryptor)(nil).GatherParticipantsData), arg0, arg1)
}
