// Code generated by MockGen. DO NOT EDIT.
// Source: governance-api-go/cmd/listener/core (interfaces: EnygmaTransactionRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/raylsnetwork/rayls-sovereign-pnh-governance/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockEnygmaTransactionRepository is a mock of EnygmaTransactionRepository interface.
type MockEnygmaTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEnygmaTransactionRepositoryMockRecorder
}

// MockEnygmaTransactionRepositoryMockRecorder is the mock recorder for MockEnygmaTransactionRepository.
type MockEnygmaTransactionRepositoryMockRecorder struct {
	mock *MockEnygmaTransactionRepository
}

// NewMockEnygmaTransactionRepository creates a new mock instance.
func NewMockEnygmaTransactionRepository(ctrl *gomock.Controller) *MockEnygmaTransactionRepository {
	mock := &MockEnygmaTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockEnygmaTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnygmaTransactionRepository) EXPECT() *MockEnygmaTransactionRepositoryMockRecorder {
	return m.recorder
}

// UpsertEnygmaTransactionsBulk mocks base method.
func (m *MockEnygmaTransactionRepository) UpsertEnygmaTransactionsBulk(ctx context.Context, enygma_transactions []*domain.EnygmaTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEnygmaTransactionsBulk", ctx, enygma_transactions)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertEnygmaTransactionsBulk indicates an expected call of UpsertEnygmaTransactionsBulk.
func (mr *MockEnygmaTransactionRepositoryMockRecorder) UpsertEnygmaTransactionsBulk(ctx, enygma_transactions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEnygmaTransactionsBulk", reflect.TypeOf((*MockEnygmaTransactionRepository)(nil).UpsertEnygmaTransactionsBulk), ctx, enygma_transactions)
}
