// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/listener/adapters/cc_provider.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	ethereum "github.com/ethereum/go-ethereum"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "github.com/golang/mock/gomock"
)

// MockEthereumClient is a mock of EthereumClient interface.
type MockEthereumClient struct {
	ctrl     *gomock.Controller
	recorder *MockEthereumClientMockRecorder
}

// MockEthereumClientMockRecorder is the mock recorder for MockEthereumClient.
type MockEthereumClientMockRecorder struct {
	mock *MockEthereumClient
}

// NewMockEthereumClient creates a new mock instance.
func NewMockEthereumClient(ctrl *gomock.Controller) *MockEthereumClient {
	mock := &MockEthereumClient{ctrl: ctrl}
	mock.recorder = &MockEthereumClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEthereumClient) EXPECT() *MockEthereumClientMockRecorder {
	return m.recorder
}

// BlockByNumber mocks base method.
func (m *MockEthereumClient) BlockByNumber(ctx context.Context, number *big.Int) (*types.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockByNumber", ctx, number)
	ret0, _ := ret[0].(*types.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockByNumber indicates an expected call of BlockByNumber.
func (mr *MockEthereumClientMockRecorder) BlockByNumber(ctx, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockByNumber", reflect.TypeOf((*MockEthereumClient)(nil).BlockByNumber), ctx, number)
}

// FilterLogs mocks base method.
func (m *MockEthereumClient) FilterLogs(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterLogs", ctx, q)
	ret0, _ := ret[0].([]types.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterLogs indicates an expected call of FilterLogs.
func (mr *MockEthereumClientMockRecorder) FilterLogs(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterLogs", reflect.TypeOf((*MockEthereumClient)(nil).FilterLogs), ctx, q)
}
