// Code generated by MockGen. DO NOT EDIT.
// Source: governance-api-go/cmd/listener/core (interfaces: HeaderProofEventRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "github.com/raylsnetwork/rayls-privacy-pnh-governance-api/domain"
	big "math/big"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHeaderProofEventRepository is a mock of HeaderProofEventRepository interface.
type MockHeaderProofEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHeaderProofEventRepositoryMockRecorder
}

// MockHeaderProofEventRepositoryMockRecorder is the mock recorder for MockHeaderProofEventRepository.
type MockHeaderProofEventRepositoryMockRecorder struct {
	mock *MockHeaderProofEventRepository
}

// NewMockHeaderProofEventRepository creates a new mock instance.
func NewMockHeaderProofEventRepository(ctrl *gomock.Controller) *MockHeaderProofEventRepository {
	mock := &MockHeaderProofEventRepository{ctrl: ctrl}
	mock.recorder = &MockHeaderProofEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHeaderProofEventRepository) EXPECT() *MockHeaderProofEventRepositoryMockRecorder {
	return m.recorder
}

// CreateBatch mocks base method.
func (m *MockHeaderProofEventRepository) CreateBatch(arg0 context.Context, arg1 []*domain.HeaderProofEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockHeaderProofEventRepositoryMockRecorder) CreateBatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockHeaderProofEventRepository)(nil).CreateBatch), arg0, arg1)
}

// Create mocks base method.
func (m *MockHeaderProofEventRepository) Create(arg0 context.Context, arg1 *domain.HeaderProofEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockHeaderProofEventRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHeaderProofEventRepository)(nil).Create), arg0, arg1)
}

// GetByBlockNumber mocks base method.
func (m *MockHeaderProofEventRepository) GetByBlockNumber(arg0 context.Context, arg1, arg2 *big.Int) (*domain.HeaderProofEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBlockNumber", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.HeaderProofEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBlockNumber indicates an expected call of GetByBlockNumber.
func (mr *MockHeaderProofEventRepositoryMockRecorder) GetByBlockNumber(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBlockNumber", reflect.TypeOf((*MockHeaderProofEventRepository)(nil).GetByBlockNumber), arg0, arg1, arg2)
}
