// Code generated by MockGen. DO NOT EDIT.
// Source: governance-api-go/cmd/listener/core (interfaces: LogParser)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	types "github.com/raylsnetwork/rayls-privacy-pnh-governance-api/cmd/listener/types"
	big "math/big"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLogParser is a mock of LogParser interface.
type MockLogParser struct {
	ctrl     *gomock.Controller
	recorder *MockLogParserMockRecorder
}

// MockLogParserMockRecorder is the mock recorder for MockLogParser.
type MockLogParserMockRecorder struct {
	mock *MockLogParser
}

// NewMockLogParser creates a new mock instance.
func NewMockLogParser(ctrl *gomock.Controller) *MockLogParser {
	mock := &MockLogParser{ctrl: ctrl}
	mock.recorder = &MockLogParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogParser) EXPECT() *MockLogParserMockRecorder {
	return m.recorder
}

// ParseLogs mocks base method.
func (m *MockLogParser) ParseLogs(arg0 context.Context, arg1, arg2 *big.Int) ([]types.ContractLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseLogs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]types.ContractLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseLogs indicates an expected call of ParseLogs.
func (mr *MockLogParserMockRecorder) ParseLogs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseLogs", reflect.TypeOf((*MockLogParser)(nil).ParseLogs), arg0, arg1, arg2)
}
