// Code generated by MockGen. DO NOT EDIT.
// Source: governance-api-go/cmd/listener/core (interfaces: ParticipantRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "github.com/raylsnetwork/rayls-privacy-pnh-governance-api/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockParticipantRepository is a mock of ParticipantRepository interface.
type MockParticipantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockParticipantRepositoryMockRecorder
}

// MockParticipantRepositoryMockRecorder is the mock recorder for MockParticipantRepository.
type MockParticipantRepositoryMockRecorder struct {
	mock *MockParticipantRepository
}

// NewMockParticipantRepository creates a new mock instance.
func NewMockParticipantRepository(ctrl *gomock.Controller) *MockParticipantRepository {
	mock := &MockParticipantRepository{ctrl: ctrl}
	mock.recorder = &MockParticipantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipantRepository) EXPECT() *MockParticipantRepositoryMockRecorder {
	return m.recorder
}

// GetByChainId mocks base method.
func (m *MockParticipantRepository) GetByChainId(arg0 context.Context, arg1 string) (domain.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByChainId", arg0, arg1)
	ret0, _ := ret[0].(domain.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByChainId indicates an expected call of GetByChainId.
func (mr *MockParticipantRepositoryMockRecorder) GetByChainId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByChainId", reflect.TypeOf((*MockParticipantRepository)(nil).GetByChainId), arg0, arg1)
}

// Upsert mocks base method.
func (m *MockParticipantRepository) Upsert(arg0 context.Context, arg1 domain.Participant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockParticipantRepositoryMockRecorder) Upsert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockParticipantRepository)(nil).Upsert), arg0, arg1)
}
