// Code generated by MockGen. DO NOT EDIT.
// Source: governance-api-go/cmd/listener/core (interfaces: RevertDataTransactionRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "github.com/raylsnetwork/rayls-privacy-pnh-governance-api/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRevertDataTransactionRepository is a mock of RevertDataTransactionRepository interface.
type MockRevertDataTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRevertDataTransactionRepositoryMockRecorder
}

// MockRevertDataTransactionRepositoryMockRecorder is the mock recorder for MockRevertDataTransactionRepository.
type MockRevertDataTransactionRepositoryMockRecorder struct {
	mock *MockRevertDataTransactionRepository
}

// NewMockRevertDataTransactionRepository creates a new mock instance.
func NewMockRevertDataTransactionRepository(ctrl *gomock.Controller) *MockRevertDataTransactionRepository {
	mock := &MockRevertDataTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockRevertDataTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRevertDataTransactionRepository) EXPECT() *MockRevertDataTransactionRepositoryMockRecorder {
	return m.recorder
}

// CreateRevertTransactions mocks base method.
func (m *MockRevertDataTransactionRepository) CreateRevertTransactions(arg0 context.Context, arg1 []*domain.RevertDataTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRevertTransactions", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRevertTransactions indicates an expected call of CreateRevertTransactions.
func (mr *MockRevertDataTransactionRepositoryMockRecorder) CreateRevertTransactions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRevertTransactions", reflect.TypeOf((*MockRevertDataTransactionRepository)(nil).CreateRevertTransactions), arg0, arg1)
}
