// Code generated by MockGen. DO NOT EDIT.
// Source: governance-api-go/cmd/listener/core (interfaces: SwapSaltsStore)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	types "github.com/raylsnetwork/rayls-privacy-pnh-governance-api/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSwapSaltsStore is a mock of SwapSaltsStore interface.
type MockSwapSaltsStore struct {
	ctrl     *gomock.Controller
	recorder *MockSwapSaltsStoreMockRecorder
}

// MockSwapSaltsStoreMockRecorder is the mock recorder for MockSwapSaltsStore.
type MockSwapSaltsStoreMockRecorder struct {
	mock *MockSwapSaltsStore
}

// NewMockSwapSaltsStore creates a new mock instance.
func NewMockSwapSaltsStore(ctrl *gomock.Controller) *MockSwapSaltsStore {
	mock := &MockSwapSaltsStore{ctrl: ctrl}
	mock.recorder = &MockSwapSaltsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSwapSaltsStore) EXPECT() *MockSwapSaltsStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSwapSaltsStore) Get(arg0 context.Context, arg1 string) (types.DvpSwapSalts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(types.DvpSwapSalts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSwapSaltsStoreMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSwapSaltsStore)(nil).Get), arg0, arg1)
}

// Put mocks base method.
func (m *MockSwapSaltsStore) Put(arg0 context.Context, arg1 string, arg2 types.DvpSwapSalts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockSwapSaltsStoreMockRecorder) Put(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockSwapSaltsStore)(nil).Put), arg0, arg1, arg2)
}
