// Code generated by MockGen. DO NOT EDIT.
// Source: governance-api-go/cmd/listener/core (interfaces: TokenRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "github.com/raylsnetwork/rayls-sovereign-pnh-governance/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTokenRepository is a mock of TokenRepository interface.
type MockTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepositoryMockRecorder
}

// MockTokenRepositoryMockRecorder is the mock recorder for MockTokenRepository.
type MockTokenRepositoryMockRecorder struct {
	mock *MockTokenRepository
}

// NewMockTokenRepository creates a new mock instance.
func NewMockTokenRepository(ctrl *gomock.Controller) *MockTokenRepository {
	mock := &MockTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepository) EXPECT() *MockTokenRepositoryMockRecorder {
	return m.recorder
}

// GetByIssuerAndName mocks base method.
func (m *MockTokenRepository) GetByIssuerAndName(arg0 context.Context, arg1, arg2 string) (*domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIssuerAndName", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIssuerAndName indicates an expected call of GetByIssuerAndName.
func (mr *MockTokenRepositoryMockRecorder) GetByIssuerAndName(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIssuerAndName", reflect.TypeOf((*MockTokenRepository)(nil).GetByIssuerAndName), arg0, arg1, arg2)
}

// GetTokenByResourceID mocks base method.
func (m *MockTokenRepository) GetTokenByResourceID(arg0 context.Context, arg1 string) (*domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenByResourceID", arg0, arg1)
	ret0, _ := ret[0].(*domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenByResourceID indicates an expected call of GetTokenByResourceID.
func (mr *MockTokenRepositoryMockRecorder) GetTokenByResourceID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenByResourceID", reflect.TypeOf((*MockTokenRepository)(nil).GetTokenByResourceID), arg0, arg1)
}

// Upsert mocks base method.
func (m *MockTokenRepository) Upsert(arg0 context.Context, arg1 *domain.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockTokenRepositoryMockRecorder) Upsert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockTokenRepository)(nil).Upsert), arg0, arg1)
}
