// Code generated by MockGen. DO NOT EDIT.
// Source: governance-api-go/cmd/listener/core (interfaces: TokenService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "github.com/raylsnetwork/rayls-sovereign-pnh-governance/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTokenService is a mock of TokenService interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// GetTokenByResourceId mocks base method.
func (m *MockTokenService) GetTokenByResourceId(arg0 context.Context, arg1 string) (*domain.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenByResourceId", arg0, arg1)
	ret0, _ := ret[0].(*domain.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenByResourceId indicates an expected call of GetTokenByResourceId.
func (mr *MockTokenServiceMockRecorder) GetTokenByResourceId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenByResourceId", reflect.TypeOf((*MockTokenService)(nil).GetTokenByResourceId), arg0, arg1)
}
