// Code generated by MockGen. DO NOT EDIT.
// Source: governance-api-go/cmd/listener/core (interfaces: TokenFreezeRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	"math/big"
	reflect "reflect"
	"time"

	gomock "github.com/golang/mock/gomock"
)

// MockTokenFreezeRepository is a mock of TokenFreezeRepository interface.
type MockTokenFreezeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenFreezeRepositoryMockRecorder
}

// MockTokenFreezeRepositoryMockRecorder is the mock recorder for MockTokenFreezeRepository.
type MockTokenFreezeRepositoryMockRecorder struct {
	mock *MockTokenFreezeRepository
}

// NewMockTokenFreezeRepository creates a new mock instance.
func NewMockTokenFreezeRepository(ctrl *gomock.Controller) *MockTokenFreezeRepository {
	mock := &MockTokenFreezeRepository{ctrl: ctrl}
	mock.recorder = &MockTokenFreezeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenFreezeRepository) EXPECT() *MockTokenFreezeRepositoryMockRecorder {
	return m.recorder
}

// UpdateTokenFreezeStatus mocks base method.
func (m *MockTokenFreezeRepository) UpdateTokenFreezeStatus(arg0 context.Context, arg1 string, arg2 []*big.Int, arg3 uint8, arg4 *big.Int, arg5 string, arg6 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTokenFreezeStatus", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTokenFreezeStatus indicates an expected call of UpdateTokenFreezeStatus.
func (mr *MockTokenFreezeRepositoryMockRecorder) UpdateTokenFreezeStatus(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTokenFreezeStatus", reflect.TypeOf((*MockTokenFreezeRepository)(nil).UpdateTokenFreezeStatus), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}
