// Code generated by MockGen. DO NOT EDIT.
// Source: governance-api-go/cmd/listener/core (interfaces: TransactionRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "github.com/raylsnetwork/rayls-sovereign-pnh-governance/domain"
	types "github.com/raylsnetwork/rayls-sovereign-pnh-governance/types"
	big "math/big"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// CreateCreditMemo mocks base method.
func (m *MockTransactionRepository) CreateCreditMemo(arg0 context.Context, arg1 *domain.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCreditMemo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCreditMemo indicates an expected call of CreateCreditMemo.
func (mr *MockTransactionRepositoryMockRecorder) CreateCreditMemo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCreditMemo", reflect.TypeOf((*MockTransactionRepository)(nil).CreateCreditMemo), arg0, arg1)
}

// CreateTransaction mocks base method.
func (m *MockTransactionRepository) CreateTransaction(arg0 context.Context, arg1 *domain.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockTransactionRepositoryMockRecorder) CreateTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).CreateTransaction), arg0, arg1)
}

// CreateTransactions mocks base method.
func (m *MockTransactionRepository) CreateTransactions(arg0 context.Context, arg1 []*domain.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactions", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransactions indicates an expected call of CreateTransactions.
func (mr *MockTransactionRepositoryMockRecorder) CreateTransactions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactions", reflect.TypeOf((*MockTransactionRepository)(nil).CreateTransactions), arg0, arg1)
}

// CreateTransactionsWithEnygmaData mocks base method.
func (m *MockTransactionRepository) CreateTransactionsWithEnygmaData(arg0 context.Context, arg1 []*domain.Transaction, arg2 []*domain.EnygmaTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactionsWithEnygmaData", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransactionsWithEnygmaData indicates an expected call of CreateTransactionsWithEnygmaData.
func (mr *MockTransactionRepositoryMockRecorder) CreateTransactionsWithEnygmaData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactionsWithEnygmaData", reflect.TypeOf((*MockTransactionRepository)(nil).CreateTransactionsWithEnygmaData), arg0, arg1, arg2)
}

// CreateTransactionsWithPromotion mocks base method.
func (m *MockTransactionRepository) CreateTransactionsWithPromotion(arg0 context.Context, arg1 []*domain.Transaction, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactionsWithPromotion", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransactionsWithPromotion indicates an expected call of CreateTransactionsWithPromotion.
func (mr *MockTransactionRepositoryMockRecorder) CreateTransactionsWithPromotion(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactionsWithPromotion", reflect.TypeOf((*MockTransactionRepository)(nil).CreateTransactionsWithPromotion), arg0, arg1, arg2)
}

// GetTransactionByMessageID mocks base method.
func (m *MockTransactionRepository) GetTransactionByMessageID(arg0 context.Context, arg1 string, arg2 bool) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByMessageID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByMessageID indicates an expected call of GetTransactionByMessageID.
func (mr *MockTransactionRepositoryMockRecorder) GetTransactionByMessageID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByMessageID", reflect.TypeOf((*MockTransactionRepository)(nil).GetTransactionByMessageID), arg0, arg1, arg2)
}

// GetTransactionsByMessageIDs mocks base method.
func (m *MockTransactionRepository) GetTransactionsByMessageIDs(arg0 context.Context, arg1 []string, arg2 bool) ([]domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsByMessageIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsByMessageIDs indicates an expected call of GetTransactionsByMessageIDs.
func (mr *MockTransactionRepositoryMockRecorder) GetTransactionsByMessageIDs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsByMessageIDs", reflect.TypeOf((*MockTransactionRepository)(nil).GetTransactionsByMessageIDs), arg0, arg1, arg2)
}

// GetTransactionsBySharedIDs mocks base method.
func (m *MockTransactionRepository) GetTransactionsBySharedIDs(arg0 context.Context, arg1 []string, arg2 bool) ([]domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsBySharedIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsBySharedIDs indicates an expected call of GetTransactionsBySharedIDs.
func (mr *MockTransactionRepositoryMockRecorder) GetTransactionsBySharedIDs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsBySharedIDs", reflect.TypeOf((*MockTransactionRepository)(nil).GetTransactionsBySharedIDs), arg0, arg1, arg2)
}

// PersistUpdateTransaction mocks base method.
func (m *MockTransactionRepository) PersistUpdateTransaction(arg0 context.Context, arg1 *types.UpdateTransaction, arg2, arg3 string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistUpdateTransaction", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PersistUpdateTransaction indicates an expected call of PersistUpdateTransaction.
func (mr *MockTransactionRepositoryMockRecorder) PersistUpdateTransaction(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistUpdateTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).PersistUpdateTransaction), arg0, arg1, arg2, arg3)
}

// PersistUpdateTransactions mocks base method.
func (m *MockTransactionRepository) PersistUpdateTransactions(arg0 context.Context, arg1 *[]types.UpdateTransaction, arg2, arg3 string) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistUpdateTransactions", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PersistUpdateTransactions indicates an expected call of PersistUpdateTransactions.
func (mr *MockTransactionRepositoryMockRecorder) PersistUpdateTransactions(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistUpdateTransactions", reflect.TypeOf((*MockTransactionRepository)(nil).PersistUpdateTransactions), arg0, arg1, arg2, arg3)
}

// UpdateDvpTeleportConfirmation mocks base method.
func (m *MockTransactionRepository) UpdateDvpTeleportConfirmation(arg0 context.Context, arg1 string, arg2 *big.Int, arg3, arg4 string, arg5 time.Time, arg6 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDvpTeleportConfirmation", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDvpTeleportConfirmation indicates an expected call of UpdateDvpTeleportConfirmation.
func (mr *MockTransactionRepositoryMockRecorder) UpdateDvpTeleportConfirmation(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDvpTeleportConfirmation", reflect.TypeOf((*MockTransactionRepository)(nil).UpdateDvpTeleportConfirmation), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// UpdateTeleportStatusBySharedID mocks base method.
func (m *MockTransactionRepository) UpdateTeleportStatusBySharedID(arg0 context.Context, arg1 string, arg2 byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeleportStatusBySharedID", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTeleportStatusBySharedID indicates an expected call of UpdateTeleportStatusBySharedID.
func (mr *MockTransactionRepositoryMockRecorder) UpdateTeleportStatusBySharedID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeleportStatusBySharedID", reflect.TypeOf((*MockTransactionRepository)(nil).UpdateTeleportStatusBySharedID), arg0, arg1, arg2)
}

// UpdateTransaction mocks base method.
func (m *MockTransactionRepository) UpdateTransaction(arg0 context.Context, arg1 *domain.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransaction indicates an expected call of UpdateTransaction.
func (mr *MockTransactionRepositoryMockRecorder) UpdateTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).UpdateTransaction), arg0, arg1)
}

// UpdateTransactionsBulk mocks base method.
func (m *MockTransactionRepository) UpdateTransactionsBulk(arg0 context.Context, arg1 []*domain.Transaction, arg2 ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateTransactionsBulk", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransactionsBulk indicates an expected call of UpdateTransactionsBulk.
func (mr *MockTransactionRepositoryMockRecorder) UpdateTransactionsBulk(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionsBulk", reflect.TypeOf((*MockTransactionRepository)(nil).UpdateTransactionsBulk), varargs...)
}
