package domain

import "time"

// DvpSwapSalts persists the two per-swap salts recovered on SwapInitiated so
// subsequent events for the same swap can reuse them across listener restarts:
//
//   - InitiatorSelfSalt: generated by the initiator, carried in the
//     DvpSwapMessage payload. The relayer encrypts SwapCompleted with it.
//   - InitiatorCtxtSalt: derived on the fly by reducing the ML-KEM shared
//     secret from the SwapInitiated Ctxt. Used to decrypt the SwapInitiated
//     payload itself and any future responder→initiator message keyed off it.
type DvpSwapSalts struct {
	SharedID          string    `gorm:"primaryKey;column:shared_id"`
	InitiatorSelfSalt []byte    `gorm:"column:initiator_self_salt;not null"`
	InitiatorCtxtSalt []byte    `gorm:"column:initiator_ctxt_salt;not null"`
	CreatedAt         time.Time `gorm:"column:created_at"`
}

func (DvpSwapSalts) TableName() string {
	return "dvp_swap_salts"
}
